set -g status-position top				# Move status bar to the top	
set -g status-style bg=default				# Give status bar transparent/default bg
set -g status-left ''					# Remove left part of the status bar
set -g status-right ''					# Remove right part of the status bar
set -g base-index 1					# Start window numbering from 1
set -g pane-base-index 1				# Start pane numbering from 1
set -g renumber-windows on				# Auto renumber windows after closing
set -g mouse on						# Enable mouse support
bind '"' split-window -c "#{pane_current_path}"		# Horizontal split opens in current dir
bind % split-window -h -c "#{pane_current_path}"	# Vertical split opens in current dir
